### ISSUE TITLE
Update Sepia to Agen 1 edition

### ISSUE THREAD

**Issue by henning-roos** [eiffel-community/eiffel-sepia#1]
### Description
Update Sepia to Agen 1 edition instead of Toulouse edition.

### Motivation
Since Agen 1 is released of the protocol, an update of sepia repository would be good to keep it up to date with the rest of eiffel.

### Exemplification
In https://eiffel-community.github.io/eiffel-sepia/ there are references to the Toulouse edition.

### Benefits
We keep the sepia repository relevant

### Possible Drawbacks
No drawbacks that I can see.

**Comment by magnusbaeck** [comment]
I'll send a PR shortly, but obviously updating the references to Paris instead of Agen.
