### ISSUE TITLE
Jenkins plugin link should be replaced with link to actual Jenkins plugin

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-sepia#6]
### Description
[activity-orchestration.html](https://github.com/eiffel-community/eiffel-sepia/blob/gh-pages/activity-orchestration.html) links to [github.com/eiffel-community/eiffel-jenkins-plugin](https://github.com/eiffel-community/eiffel-jenkins-plugin) but that repository is empty and should probably be deleted. The only known Jenkins plugin implementation of Eiffel is [github.com/jenkinsci/eiffel-broadcaster-plugin](https://github.com/jenkinsci/eiffel-broadcaster-plugin) and the link should reflect that.

### Motivation
There's no reason to link to an abandoned repository.

### Exemplification
N/A

### Benefits
Obvious. Granting visibility to the eiffel-broadcaster plugin is of particular importance since it lives outside the eiffel-community organization and therefore is harder to find.

### Possible Drawbacks
None.

**Comment by d-stahl-ericsson** [comment]
Right. I guess the idea was that Ericsson would license its internal Jenkins plugin and put it here, but it's been three years. It doesn't seem to be happening? @e-backmark-ericsson, @k-hallen-ericsson, @m-linner-ericsson or @henning-roos know anything about that?

If it's not happening, then it's obviously better to point to a live repo than a dead one :)

**Comment by m-linner-ericsson** [comment]
Closing due to merging of https://github.com/eiffel-community/eiffel-sepia/pull/7
