### ISSUE TITLE
Document RabbitMQ routing key schema as a SHOULD requirement

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-sepia#8]
### Description
There is currently no established schema for the routing keys used when publishing messages. Therefore some publishers have picked their own schema (notably REMReM Publish) while others just use a generic and not very useful routing key like "eiffel". 

The end result is that consumers can't have useful routing key patterns in the exchange bindings for their queues, i.e. they have to consume all events and filter them client-side. This is computationally wasteful and wastes network bandwidth (though probably only significant over congested WAN links). It could also cause problems if the broker imposes a maximum queue length to protect itself from misbehaving clients. If a consumer is unavailable there will be a build-up of messages in its queue regardless of whether any of those messages are of interest, and there's a risk that interesting messages get pushed out from the queue to make room for uninteresting messages.

We should update [rabbitmq-message-broker.html](https://github.com/eiffel-community/eiffel-sepia/blob/gh-pages/rabbitmq-message-broker.html) and document a routing key standard that publishers SHOULD follow.

Suggestion:

    eiffel.<event type>.<tag>.<domain>

Example:

    eiffel.EiffelCompositionDefinedEvent.notag.example.com

This is very similar to the routing key employed by REMReM Generate except that we use the event type instead of two discrete values whose value spaces aren't well-defined.

### Motivation
See above.

### Exemplification
See below.

### Benefits
Useful routing keys for published messages will enable clients to filter incoming messages. This has a number of concrete benefits:

- No CPU cycles wasted on the consumer side.
- No bandwidth waste.
- Less broker CPU usage.
- When the length of the queue more closely matches the actual remaining work for a consumer it'll be easier to set queue length based alerts (i.e. nobody will get paged in the middle of night just because someone has published gobs of messages that the queue's consumer doesn't care about).
- Decreased risk of message loss when queue max length policies are in place in the broker.

### Possible Drawbacks
Existing implementations may have to adjust their routing key schema. Such a change should be seen as backwards incompatible so some kind of migration path would be required.

**Comment by e-backmark-ericsson** [comment]
Sorry @magnusbaeck  for a _very_ late reply on this. We do currently follow the routing key schema defined in [REMReM Semantics](https://github.com/eiffel-community/eiffel-remrem-semantics/blob/master/wiki/templates.md). We think it is quite good to be able to limit the message routing on not just event type but also on event family. Unfortunately the family definitions are not defined in the protocol itself, but only in the REMReM part. My suggestion is that we keep the possibility to provide a family entry in the routing key as well, but of course it does not need to be used if not wanted.

Additionaly, we'd need the possibility to describe more parts of the sender apart from the domainId, such as site and component

So, my suggested routing key pattern would be the one described in [REMReM Semantics](https://eiffel-community.github.io/eiffel-remrem-semantics/routingAndBindingKeyConcepts.html), i.e. "eiffel.<family>.<type>.<tag>.<domain>.<site>.<component>", or if we don't want to state site and component explicitly we could instead state "eiffel.<family>.<type>.<tag>.<source>", where <source> could contain "dots" and should represent the information given in meta.source in one way or another.

Of course the <family> part could be optional in the same way the <tag> is in your proposal.

And if we would include the family part in this proposal, we would need to define the event families in the protocol repository as well.

**Comment by d-stahl-ericsson** [comment]
It seems to me there is a philosophical issue that needs to be resolved first: should the architecture dictate the routing key scheme, or should it be a deployment decision?

Currently, the architecture doesn't dictate. That could work, but then each implementation needs to leave it completely open to deployment-time configuration. As it stands, implementations (e.g. Remrem) are de facto defining the routing key scheme on their own, which gives us the worst of two worlds.

So either we think it should be a deployment time decision, and then we need to be very clear that the implementation shouldn't dictate it. Or we think it should be an architectural decision, and then we need to first agree on what it should be, and second bring all implementations in line.

**Comment by magnusbaeck** [comment]
This sounds like a topic for a TC meeting. Perhaps you'd like to participate @d-stahl-ericsson? There's an opportunity this afternoon at 13:00 (or the same time in two weeks).

I agree that there's a choice to be made here. I don't have a strong opinion in the matter but I do think there are a couple of advantages of standardizing on a routing key schema:

* It's probably easier for the publishers to follow a standard pattern instead of providing a configuration option with template string interpolation etc.
* Those responsible for deploying Eiffel publishers probably prefer to minimize the number of configuration options. Given that Eiffel actors are written in different languages with different frameworks I'm sure that the routing key template string won't be compatible between different tools, i.e. it's not just a matter of copying the template string between publisher configuration files.

Making the routing key site-configurable is of course more flexible, but I wonder if everyone's willing to pay for that flexibility.

It's not immediately clear why the event family is deemed important. A queue can have multiple bindings to an exchange so as long as the event name is present in the routing key it's totally possible to subscribe to e.g. all artifact events.

**Comment by m-linner-ericsson** [comment]
As Sepia suggests using RabbitMQ it would be beneficial to describe the routing scheme in the sepia documentation to find all recommendation information in place. REMReM semantics should link to this.

As @e-backmark-ericsson suggested above: What about `eiffel.<family/super type>.<type>.<tag>.<domainid>`? where domain id is
>Description: Identifies the domain that produced an event. A domain is an infrastructure topological concept, which may or may not corresponds to an organization or product structures. A good example would be Java packages notation, ex. com.mycompany.product.component or mycompany.site.division. Also, keep in mind that all names are more or less prone to change. Particularly, it is recommended to avoid organizational names or site names, as organizations tend to be volatile and development is easily relocated. Relatively speaking, product and component names tend to be more stable and are therefore encouraged, while code names may be an option. You need to decide what is the most sensible option in your case.

**Comment by magnusbaeck** [comment]
I'm okay with including the family in the routing key (especially if it's optional) as long as the families are defined somewhere. Emil hints at the protocol repo, but I'm not sure I'd rule out putting it in this repo. I've put this on the agenda of tomorrow's TC meeting.

**Comment by e-backmark-ericsson** [comment]
The event family should/could be synched with the grouping used for Pipeline Actors in Sepia here: https://eiffel-community.github.io/eiffel-sepia/

**Comment by e-backmark-ericsson** [comment]
On a deeper thought I still think it would be very valuable to re-use those "actor roles" defined in Sepia as event family/super type in the routing keys. Those actor roles might need to be revisited first, both w.r.t. their names and also w.r.t. their definitions. We should also provide an abbreviated name for each role, with low caps and only letters, to be used in the routing key.

**Comment by magnusbaeck** [comment]
Looking at the pipeline actor roles I'm a wee bit worried that the categorization won't be so useful in practice. The roles are quite granular so many of them contain very few event types and thus most consumers will have to set up multiple routing keys in their queue bindings anyway (or they'll just bind to `#` and deal with the fire hose of events that ensues). Engineers are prone to over-categorizing things so I want to make sure we're doing it for the right reasons here.

**Comment by e-backmark-ericsson** [comment]
I agree, that's one reason for mentioning that those roles might need to be revisited. We could either join some of them, or create another level of super roles to group them if we think that is better. Let's discuss it briefly in the TC today if we get the time for it.

**Comment by m-linner-ericsson** [comment]
We need to review these roles and their content, but I would agree with Emil that it could be good to have some possibility to group events.

**Comment by magnusbaeck** [comment]
See the related discussion about event categorization in #10. What we could do is define the routing key schema as `eiffel.<family>.<type>.<tag>.<domainid>` as discussed earlier _but not define the family field_. This leaves us with a placeholder field that we can define at a later point in time when the whole categorization discussion has settled while still enabling clients to immediately start filtering on the defined fields, like `<type>`. Well, "immediately" as in "when relevant producers start adhering to the new standard", but that could happen pretty soon in many cases.

**Comment by magnusbaeck** [comment]
At the 2021-07-01 TC meeting I got an action to check the maximum length of a single RabbitMQ routing key and the limit on the number of bindings for a queue. According to https://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2011-August/014551.html the routing key can't be longer than 255 characters (as limited by the AMQP 0.9.1 spec), and https://groups.google.com/g/rabbitmq-users/c/9Etlwfxo4NA/m/K5kjRnwMAwAJ says that RabbitMQ doesn't enforce a limit on the number of bindings per queue.
